subjects:
  theorycs: 
    name: Theory CS
    color: "#fae48f"
  ml: 
    name: ML
    color: "#8ffacf"
  se: 
    name: Software
    color: "#70d5ff"
  ai:
    name: AI
    color: "#9bceff"
  neuro: 
    name: Neurosci
    color: "#b8ffc3"
  comp: 
    name: Computer Science
    color: "#33fff5"
  math: 
    name: Math
    color: "#9b92c3"
jobs:
  teaching: 
    name: Teaching
    color: "#FF8C00"
  research:
    name: Research
    color: "#8A2BE2"